[package]
name = "windows_input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.7"
winapi = { version = "0.3.9", features = ["winuser", "windef", "errhandlingapi"] }